object Dependencies {
    const val composeUI = "androidx.compose.ui:ui:${Versions.composeBaseVersion}"
    const val composeTooling = "androidx.compose.ui:ui-tooling:${Versions.composeBaseVersion}"
    const val composeFoundation = "androidx.compose.foundation:foundation:${Versions.composeBaseVersion}"
    const val composeMaterial = "androidx.compose.material:material:${Versions.composeBaseVersion}"
    const val composeUiTest = "androidx.compose.ui:ui-test-junit4:${Versions.composeBaseVersion}"
    const val composeViewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.composeViewModelVersion}"
    const val composeActivity = "androidx.activity:activity-compose:${Versions.composeActivityVersion}"
    const val composeNavigation = "androidx.navigation:navigation-compose:${Versions.composeNavigationVersion}"
    const val composeMaterialIcons = "androidx.compose.material:material-icons-extended:${Versions.composeBaseVersion}"
    const val mpChart = "com.github.PhilJay:MPAndroidChart:${Versions.mpChartVersion}"
    const val jupiter = "org.junit.jupiter:junit-jupiter-api:${Versions.jupiterVersion}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlinxCoroutinesCore}"
    const val composeSystemUiController = "com.google.accompanist:accompanist-systemuicontroller:${Versions.composeSystemUiController}"
    const val composeKoin = "io.insert-koin:koin-androidx-compose:${Versions.composeKoinVersion}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofitVersion}"
    const val koin = "io.insert-koin:koin-core:${Versions.koinVersion}"
    const val gsonRetrofit = "com.squareup.retrofit2:converter-gson:${Versions.retrofitVersion}"
    const val retrofitLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.logginInterceptor}"
    const val dataStore = "androidx.datastore:datastore-preferences:${Versions.dataStoreVersion}"

}