object Versions {
    const val dataStoreVersion = "1.0.0"
    const val logginInterceptor = "4.10.0"
    const val retrofitVersion = "2.9.0"
    const val jupiterVersion = "5.8.2"
    const val kotlinxCoroutinesCore = "1.6.0"
    const val composeBaseVersion = "1.2.1"
    const val composeViewModelVersion = "2.5.1"
    const val kotlinCompilerExtensionVersion = "1.3.0"
    const val composeActivityVersion = "1.5.1"
    const val composeNavigationVersion = "2.5.1"
    const val mpChartVersion = "v3.1.0"
    const val composeSystemUiController = "0.27.0"
    const val koinVersion = "3.2.2"
    const val composeKoinVersion = "3.3.0"
    const val composePagerVersion = "0.27.1"
}